Repository microsoft/lightgbm-benchmark, pull requests merged in 2022-01, with the labels that each got.

#212 Upgrade to latest shrike+azuremlsdk, add tags to datasets
  requirements.txt
  src/pipelines/azureml/data_generation.py
Labels: enhancement

#211 Generate bigger synthetic data using per-batch generation [regression only]
  requirements.txt
  src/common/data.py
  src/common/tasks.py
  src/pipelines/azureml/data_generation.py
  src/scripts/data_processing/generate_data/generate.py
  src/scripts/data_processing/generate_data/spec.yaml
  tests/common/test_data.py
  tests/scripts/test_generate_data.py
Labels: enhancement

#213 Fix docs on Designer UI by using rel paths
  .github/workflows/codeql-analysis.yml
  docs/run/azureml/designer-ui.md
Labels: bug, documentation

#216 Add url after submit, and show warning to add +run.submit=true
  src/common/components.py
  src/common/pipelines.py
Labels: enhancement

#215 Implement Lightgbm/Ray for inferencing with new RayScript helper class for AzureML integration
  conf/experiments/benchmarks/lightgbm-inferencing.yaml
  conf/experiments/lightgbm-inferencing.yaml
  requirements.txt
  src/common/ray.py
  src/pipelines/azureml/lightgbm_inferencing.py
  src/scripts/inferencing/lightgbm_ray/.amlignore
  src/scripts/inferencing/lightgbm_ray/default.dockerfile
  src/scripts/inferencing/lightgbm_ray/score.py
  src/scripts/inferencing/lightgbm_ray/spec.additional_includes
  src/scripts/inferencing/lightgbm_ray/spec.yaml
  tests/aml/test_components.py
  tests/scripts/test_lightgbm_inferencing_ray.py
Labels: enhancement

#214 added ranking data generation
  conf/experiments/data-generation.yaml
  src/common/data.py
  src/common/tasks.py
  src/pipelines/azureml/data_generation.py
  src/scripts/data_processing/generate_data/generate.py
  src/scripts/data_processing/generate_data/spec.yaml
  tests/common/test_data.py
  tests/scripts/test_generate_data.py
Labels: enhancement, training-benchmark

#221 Add readable "display name" for each step
  src/common/aml.py
  src/pipelines/azureml/data_generation.py
  src/pipelines/azureml/lightgbm_inferencing.py
  src/pipelines/azureml/lightgbm_training.py
  tests/common/test_aml.py
Labels: enhancement

#222 Implement log_artifact methods in metrics logger
  src/common/metrics.py
  tests/common/test_metrics.py
Labels: enhancement

#220 Add header in synthetic data generator
  src/common/tasks.py
  src/pipelines/azureml/data_generation.py
  src/scripts/data_processing/generate_data/generate.py
  src/scripts/data_processing/generate_data/spec.yaml
  tests/scripts/test_generate_data.py
Labels: enhancement

#227 HotFix: specify pip version that works for our build
  .github/workflows/azureml_pipelines.yml
  .github/workflows/benchmark_scripts.yml
Labels: bug

#226 Add perf reporting to RayScript class
  src/common/ray.py
Labels: enhancement

#225 Add header in test data and unit tests
  tests/data/regression/model/model.txt
  tests/data/regression/test/test.txt
  tests/data/regression/train/train.txt
  tests/scripts/test_lightgbm_data2bin.py
  tests/scripts/test_lightgbm_python.py
  tests/scripts/test_partition_data.py
Labels: bug
